<?php

namespace Database\Seeders\Admin;

use App\Models\Admin\TopUpGame;
use Illuminate\Database\Seeder;

class TopUpGameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $top_up_games = array(
            array('id' => '1', 'title' => '8 Ball Pool', 'slug' => '8-ball-pool', 'description' => 'Top up Modern Combat 5: Blackout Credits and VIP Points in seconds! Just enter your Modern Combat 5: Blackout user ID, select the value of Credits and VIP Points you wish to purchase, complete the payment, and the Credits and VIP Points will be added immediately to your Modern Combat 5: Blackout account.

                    Pay with convenience using bKash and Robi. There\'s no credit card, registration, or log-in required!', 'google_store' => '#', 'apple_store' => '##', 'profile_image' => '0e1de3d0-0786-462a-8590-0d5626409070.webp', 'cover_image' => '79bf3c9f-d34c-4c01-8ed8-ec285db2619d.webp', 'input_fields' => '{"input_fields_player_id":[{"name":"player_id","label":"Player ID","required":true,"type":"text"},{"name":"client_id","label":"User ID","required":true,"type":"text"}],"input_fields_recharge":[{"credit_amount":"10","type":"coin","currency_amount":"20"},{"credit_amount":"20","type":"coin","currency_amount":"25"}]}', 'status' => '1', 'created_at' => '2023-09-09 10:10:08', 'updated_at' => '2023-09-09 10:10:08'),
            array('id' => '2', 'title' => 'Asphalt 9: Legends', 'slug' => 'asphalt-9-legends', 'description' => 'Top up Modern Combat 5: Blackout Credits and VIP Points in seconds! Just enter your Modern Combat 5: Blackout user ID, select the value of Credits and VIP Points you wish to purchase, complete the payment, and the Credits and VIP Points will be added immediately to your Modern Combat 5: Blackout account.

                    Pay with convenience using bKash and Robi. There\'s no credit card, registration, or log-in required!', 'google_store' => NULL, 'apple_store' => NULL, 'profile_image' => '0be3bdaa-82e3-412f-8709-728254e9f001.webp', 'cover_image' => '5cbd15a0-efdb-46e9-9cfb-298959b92859.webp', 'input_fields' => '{"input_fields_player_id":[{"name":"player_tag","label":"Player Tag","required":true,"type":"text"}],"input_fields_recharge":[{"credit_amount":"100","type":"gem","currency_amount":"10"},{"credit_amount":"50","type":"gem","currency_amount":"5"}]}', 'status' => '1', 'created_at' => '2023-09-09 10:11:43', 'updated_at' => '2023-09-09 10:11:43'),
            array('id' => '3', 'title' => 'Minecraft', 'slug' => 'minecraft', 'description' => 'Top up Modern Combat 5: Blackout Credits and VIP Points in seconds! Just enter your Modern Combat 5: Blackout user ID, select the value of Credits and VIP Points you wish to purchase, complete the payment, and the Credits and VIP Points will be added immediately to your Modern Combat 5: Blackout account.

                    Pay with convenience using bKash and Robi. There\'s no credit card, registration, or log-in required!', 'google_store' => NULL, 'apple_store' => NULL, 'profile_image' => '5e899850-dae2-4370-a144-576b3fd43caf.webp', 'cover_image' => '5d48b37b-f196-4827-8b48-94dca78a8f39.webp', 'input_fields' => '{"input_fields_player_id":[{"name":"player_id","label":"Player ID","required":true,"type":"text"}],"input_fields_recharge":[{"credit_amount":"10","type":"diamond","currency_amount":"1"},{"credit_amount":"20","type":"diamond","currency_amount":"2"}]}', 'status' => '1', 'created_at' => '2023-09-09 10:14:05', 'updated_at' => '2023-09-09 10:14:05'),
            array('id' => '4', 'title' => 'World War Heroes', 'slug' => 'world-war-heroes', 'description' => 'Top up Modern Combat 5: Blackout Credits and VIP Points in seconds! Just enter your Modern Combat 5: Blackout user ID, select the value of Credits and VIP Points you wish to purchase, complete the payment, and the Credits and VIP Points will be added immediately to your Modern Combat 5: Blackout account.

                    Pay with convenience using bKash and Robi. There\'s no credit card, registration, or log-in required!', 'google_store' => NULL, 'apple_store' => NULL, 'profile_image' => '281985ef-6f62-49f0-b4ee-ed102228a6da.webp', 'cover_image' => '2474840d-a5a4-4aa7-bff9-6e574a1232f2.webp', 'input_fields' => '{"input_fields_player_id":[{"name":"user_id","label":"User ID","required":true,"type":"text"}],"input_fields_recharge":[{"credit_amount":"10","type":"point","currency_amount":"20"},{"credit_amount":"20","type":"point","currency_amount":"15"},{"credit_amount":"30","type":"point","currency_amount":"20"}]}', 'status' => '1', 'created_at' => '2023-09-09 10:17:09', 'updated_at' => '2023-09-09 10:17:09'),
            array('id' => '5', 'title' => 'Mobile Legends', 'slug' => 'mobile-legends', 'description' => 'Top up Modern Combat 5: Blackout Credits and VIP Points in seconds! Just enter your Modern Combat 5: Blackout user ID, select the value of Credits and VIP Points you wish to purchase, complete the payment, and the Credits and VIP Points will be added immediately to your Modern Combat 5: Blackout account.

                    Pay with convenience using bKash and Robi. There\'s no credit card, registration, or log-in required!', 'google_store' => '#', 'apple_store' => '##', 'profile_image' => '50513084-976b-4b67-9ff7-e06749698ac5.webp', 'cover_image' => '93c3ae25-13f3-40af-8005-4b839168e4f2.webp', 'input_fields' => '{"input_fields_player_id":[{"name":"player_id","label":"Player ID","required":true,"type":"text"}],"input_fields_recharge":[{"credit_amount":"10","type":"code","currency_amount":"5"},{"credit_amount":"20","type":"code","currency_amount":"8"},{"credit_amount":"30","type":"code","currency_amount":"15"}]}', 'status' => '1', 'created_at' => '2023-09-09 10:18:42', 'updated_at' => '2023-09-09 10:18:42'),
            array('id' => '6', 'title' => 'Top Eleven', 'slug' => 'top-eleven', 'description' => 'Top up Modern Combat 5: Blackout Credits and VIP Points in seconds! Just enter your Modern Combat 5: Blackout user ID, select the value of Credits and VIP Points you wish to purchase, complete the payment, and the Credits and VIP Points will be added immediately to your Modern Combat 5: Blackout account.

                    Pay with convenience using bKash and Robi. There\'s no credit card, registration, or log-in required!', 'google_store' => NULL, 'apple_store' => NULL, 'profile_image' => '58024549-9244-40bc-85a7-ef57158368fa.webp', 'cover_image' => '4a8acd2b-6e82-40ba-be0a-879dc0e91234.webp', 'input_fields' => '{"input_fields_player_id":[{"name":"user_id","label":"User ID","required":true,"type":"text"}],"input_fields_recharge":[{"credit_amount":"5","type":"gem","currency_amount":"10"},{"credit_amount":"10","type":"gem","currency_amount":"15"}]}', 'status' => '1', 'created_at' => '2023-09-09 10:20:03', 'updated_at' => '2023-09-09 10:20:03'),
            array('id' => '7', 'title' => 'Grand Theft Auto V', 'slug' => 'grand-theft-auto-v', 'description' => 'Top up Modern Combat 5: Blackout Credits and VIP Points in seconds! Just enter your Modern Combat 5: Blackout user ID, select the value of Credits and VIP Points you wish to purchase, complete the payment, and the Credits and VIP Points will be added immediately to your Modern Combat 5: Blackout account.

                    Pay with convenience using bKash and Robi. There\'s no credit card, registration, or log-in required!', 'google_store' => NULL, 'apple_store' => NULL, 'profile_image' => 'f8d63484-a3cf-4cff-b131-66eb5a4e3b2d.webp', 'cover_image' => '1d02ff66-3e51-4da8-9557-5f455b9f7ebb.webp', 'input_fields' => '{"input_fields_player_id":[{"name":"user_id","label":"User ID","required":true,"type":"text"}],"input_fields_recharge":[{"credit_amount":"5","type":"credit","currency_amount":"10"},{"credit_amount":"10","type":"credit","currency_amount":"8"},{"credit_amount":"20","type":"credit","currency_amount":"12"}]}', 'status' => '1', 'created_at' => '2023-09-09 10:21:13', 'updated_at' => '2023-09-09 10:21:13'),
            array('id' => '8', 'title' => 'Modern Strike', 'slug' => 'modern-strike', 'description' => 'Top up Modern Combat 5: Blackout Credits and VIP Points in seconds! Just enter your Modern Combat 5: Blackout user ID, select the value of Credits and VIP Points you wish to purchase, complete the payment, and the Credits and VIP Points will be added immediately to your Modern Combat 5: Blackout account.

                    Pay with convenience using bKash and Robi. There\'s no credit card, registration, or log-in required!', 'google_store' => '#', 'apple_store' => '##', 'profile_image' => '273f96d0-f7bd-4ee9-8838-8a525c9332b4.webp', 'cover_image' => '98bb2eba-2e22-4e52-93e5-a1476f0eaa97.webp', 'input_fields' => '{"input_fields_player_id":[{"name":"user_id","label":"User ID","required":true,"type":"text"}],"input_fields_recharge":[{"credit_amount":"10","type":"coin","currency_amount":"5"},{"credit_amount":"20","type":"coin","currency_amount":"8"},{"credit_amount":"30","type":"coin","currency_amount":"12"}]}', 'status' => '1', 'created_at' => '2023-09-09 10:22:36', 'updated_at' => '2023-09-09 10:22:36'),
            array('id' => '9', 'title' => 'Ludo Club', 'slug' => 'ludo-club', 'description' => 'The value of Credits and VIP Points you wish to purchase, complete the payment, and the Credits and VIP Points will be added immediately to your Modern Combat 5: Blackout account. Pay with convenience using bKash and Robi. There\'s no credit card, registration, or log-in required!', 'google_store' => NULL, 'apple_store' => NULL, 'profile_image' => 'bac69339-1f2a-4757-a7fb-c79ca5931b56.webp', 'cover_image' => '16746b1d-bbe2-46fd-8e2c-cc6f6eb42d51.webp', 'input_fields' => '{"input_fields_player_id":[{"name":"user_id","label":"User ID","required":true,"type":"text"}],"input_fields_recharge":[{"credit_amount":"10","type":"coin","currency_amount":"100"}]}', 'status' => '1', 'created_at' => '2023-09-14 10:43:16', 'updated_at' => '2023-09-14 10:43:16'),
            array('id' => '10', 'title' => 'Carrom Gold', 'slug' => 'carrom-gold', 'description' => 'Just enter your Modern Combat 5: Blackout user ID, select the value of Credits and VIP Points you wish to purchase, complete the payment, and the Credits and VIP Points will be added immediately to your Modern Combat 5: Blackout account. Pay with convenience using bKash and Robi. There\'s no credit card, registration, or log-in required!', 'google_store' => NULL, 'apple_store' => NULL, 'profile_image' => '9d50b10e-639c-4cb5-96e3-8b1dcb90acbe.webp', 'cover_image' => 'b9f576f7-714a-4b96-a8c5-5a2928edb457.webp', 'input_fields' => '{"input_fields_player_id":[{"name":"player_id","label":"Player ID","required":true,"type":"text"}],"input_fields_recharge":[{"credit_amount":"10","type":"diamond","currency_amount":"10"}]}', 'status' => '1', 'created_at' => '2023-09-14 10:44:34', 'updated_at' => '2023-09-14 10:44:34'),
            array('id' => '11', 'title' => 'Be The King: Judge Destiny', 'slug' => 'be-the-king-judge-destiny', 'description' => 'Complete the payment, and the Credits and VIP Points will be added immediately to your Modern Combat 5: Blackout account. Pay with convenience using bKash and Robi. There\'s no credit card, registration, or log-in required!', 'google_store' => NULL, 'apple_store' => NULL, 'profile_image' => '92727b32-ece7-4096-91f7-ed18666af633.webp', 'cover_image' => '0a068a2b-1b6f-490e-a5f7-d961bf928acc.webp', 'input_fields' => '{"input_fields_player_id":[{"name":"user_id","label":"User ID","required":true,"type":"text"}],"input_fields_recharge":[{"credit_amount":"10","type":"point","currency_amount":"10"}]}', 'status' => '1', 'created_at' => '2023-09-14 10:45:55', 'updated_at' => '2023-09-14 10:45:55'),
            array('id' => '12', 'title' => 'Clash of Clans', 'slug' => 'clash-of-clans', 'description' => 'Points you wish to purchase, complete the payment, and the Credits and VIP Points will be added immediately to your Modern Combat 5: Blackout account. Pay with convenience using bKash and Robi. There\'s no credit card, registration, or log-in required!', 'google_store' => NULL, 'apple_store' => NULL, 'profile_image' => 'd6a9159b-e747-4395-b39d-0313995a20cb.webp', 'cover_image' => '91d7ea64-108f-4554-b738-8777b016a953.webp', 'input_fields' => '{"input_fields_player_id":[{"name":"player_id","label":"Player ID","required":true,"type":"text"}],"input_fields_recharge":[{"credit_amount":"10","type":"coin","currency_amount":"10"}]}', 'status' => '1', 'created_at' => '2023-09-14 10:46:49', 'updated_at' => '2023-09-14 10:46:49')
        );
        TopUpGame::insert($top_up_games);
    }
}
